# Generated by Django 5.1.2 on 2025-07-21 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_contrato_duracion_del_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_de_fin_del_contrato',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_de_firma',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_de_inicio_del_contrato',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_de_notificacion_de_prorroga',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_fin_liquidacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio_liquidacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 7, 21, 22, 24, 32, 602427, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
