# Generated by Django 5.1.2 on 2025-09-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_contrato_fecha_de_fin_del_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoInteradministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_entidad', models.CharField(blank=True, max_length=100)),
                ('codigo_entidad_en_secop', models.CharField(blank=True, max_length=50)),
                ('nombre_de_la_entidad', models.CharField(blank=True, max_length=255)),
                ('nit_de_la_entidad', models.CharField(blank=True, max_length=50)),
                ('departamento_entidad', models.CharField(blank=True, max_length=100)),
                ('municipio_entidad', models.CharField(blank=True, max_length=100)),
                ('estado_del_proceso', models.CharField(blank=True, max_length=100)),
                ('modalidad_de_contrataci_n', models.CharField(blank=True, max_length=100)),
                ('objeto_a_contratar', models.TextField(blank=True)),
                ('objeto_del_proceso', models.TextField(blank=True)),
                ('tipo_de_contrato', models.CharField(blank=True, max_length=100)),
                ('fecha_de_firma_del_contrato', models.DateField(blank=True, null=True)),
                ('fecha_inicio_ejecuci_n', models.DateField(blank=True, null=True)),
                ('fecha_fin_ejecuci_n', models.DateField(blank=True, null=True)),
                ('numero_del_contrato', models.CharField(blank=True, max_length=100)),
                ('numero_de_proceso', models.CharField(max_length=100, unique=True)),
                ('valor_contrato', models.BigIntegerField(default=0)),
                ('nom_raz_social_contratista', models.CharField(blank=True, max_length=255)),
                ('tipo_documento_proveedor', models.CharField(blank=True, max_length=50)),
                ('documento_proveedor', models.CharField(blank=True, max_length=50)),
                ('url_contrato', models.URLField(blank=True, max_length=500)),
                ('origen', models.CharField(blank=True, max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrato Interadministrativo',
                'verbose_name_plural': 'Contratos Interadministrativos',
                'ordering': ['-fecha_de_firma_del_contrato'],
            },
        ),
    ]
